version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.claude:/home/vscode/.claude:cached
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig:cached
      - ${HOME}/.config/gh:/home/vscode/.config/gh:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:cached
    environment:
      - PYTHONPATH=/workspace
    command: sleep infinity
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined