name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8
    
    - name: Check code formatting
      run: |
        black --check main.py test_api.py
    
    - name: Lint code
      run: |
        flake8 main.py test_api.py --max-line-length=127
    
    - name: Build C++ extension
      run: |
        python setup.py build_ext --inplace
    
    - name: Quick smoke test
      run: |
        python -c "import main; print('Import successful')"
        python -c "import fibonacci_cpp; print('C++ module loaded:', fibonacci_cpp.fibonacci_iterative(10))"